# fly.toml app configuration file generated for nginx-cluster-next on 2024-05-16T15:03:29-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nginx-cluster-next'
primary_region = 'sea'

[experimental]

[build]

[[mounts]]
  source = 'nginx_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
